### ISSUE TITLE
메인현황판 - 날씨 데이터 표기오류

### ISSUE THREAD

**Issue by endless87** [darkness87/AMISystem#30]
![image.png](https://images.zenhubusercontent.com/5f27b089a9416e6cd5a2ba78/79e029af-1c40-448b-b57f-b8c1d2ad98ed)

날씨 온도 미구현

**Comment by darkness87** [comment]
오늘의 날씨 영역의 li 구분을 '/'가 아닌 한줄씩 표기되도록 만들어야 온전하게 표기될수 있을거같아요!
